### ISSUE TITLE
Occasional run-on sentences and random grammar tweaks

### ISSUE THREAD

**Issue by ClimbsRocks** [toddmotto/toddmotto.github.io#24]
This is a great site! It came highly recommended from a friend who has, in his free time, rewritten most of Angular's functionality for fun. 

As I'm reading through it, I've noticed a number of run-on sentences and other random grammatical issues. If you're open to it, I'd be happy to submit pull requests for them. Just wanted to check and see if you had any preferences before I made too many tweaks.

**Comment by toddmotto** [comment]
Thanks for the PRs, really appreciate it :) sometimes grammar gets the better of me ;)
