### ISSUE TITLE
License for Super Simple Drop Down Nav

### ISSUE THREAD

**Issue by jasonparallel** [toddmotto/toddmotto.github.io#46]
License.txt simply provides the link toddmotto.com/licensing. This link returns a 404 error. Please clarify licensing or fix toddmotto.com/licensing.

**Comment by toddmotto** [comment]
This page was removed a while back, licensing info is here:
toddmotto.com/about

On 10 February 2016 at 00:23, jasonparallel <notifications@github.com>
wrote:

> License.txt simply provides the link toddmotto.com/licensing. This link
> returns a 404 error. Please clarify licensing or fix
> toddmotto.com/licensing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toddmotto/toddmotto.github.io/issues/46>.
>



-- 
@toddmotto
